export enum BookCategory {
  Fiction = 'Fiction',
  NonFiction = 'Non-Fiction',
  Science = 'Science',
  History = 'History',
  Politics = 'Politics',
  Biography = 'Biography',
  Fantasy = 'Fantasy',
  Mystery = 'Mystery',
  Romance = 'Romance',
  Thriller = 'Thriller',
  SelfHelp = 'Self-Help',
  Business = 'Business',
  Technology = 'Technology',
  Art = 'Art',
  Poetry = 'Poetry',
  Children = 'Children',
}
